apiVersion: v1
data:
  gitea-backup.yml: |
    gitea_backup:
      debug: {{ .Values.gitea_backup.config.debug | quote }}
      stopOnFailure: {{ .Values.gitea_backup.config.stopOnFailure | quote }}
      {{- with .Values.gitea_backup.config.sources }}
      sources:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.gitea_backup.config.remotes }}
      remotes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.gitea_backup.config.backups }}
      backups:
        {{- toYaml . | nindent 8 }}
      {{- end }}

kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace | quote }}
  name: {{ template "gitea_backup.fullname" . }}-config

